sudo: required
language: bash

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - docker login -u $DOCKER_USER -p $REGISTRY_TOKEN
#   - export REPO=AlexSkibaYojji/docker-react-native-fastlane
#   - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO .

after_success:
#   - docker tag $REPO:$COMMIT $REPO:$TAG
#   - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
#   - docker push $REPO:travis-$TRAVIS_BUILD_NUMBER
